name = "inventory-jj"
compatibility_date = "2024-09-23"
main = "./dist/server/entry.mjs"

[assets]
directory = "./dist/client"
binding = "ASSETS"

[[kv_namespaces]]
binding = "INVENTORY_KV"
id = "a4641925e7884923b41828e41d428f57"
